print('1) Who developed pyhton programming language?')
print('=> Guido van Rossum.')
print('2) Which type of programming does python support?')
print('=> Python supports four main programming paradigms: imperative, functional, procedural, and object-oriented.')
print('3) Is Python case sensitive when dealing with identifiers?')
print('=> Yes, Python is a case-sensitive language.')
print('4) What is the correct extension of Python file?')
print('=> .py')
print('5) Is Python code is compiled or interpreted?')
print('=> Python is an interpreted language.')
print('6) Name a few blocks of code use to define in Python language?')
print('=> The following are blocks: a module, a function body, and a class definition.')
print('7) State a character used to give single line comments in Python?')
print('=> The following are blocks: a module, a function body, and a class definition.')
print('8) Mention function which can help us to find the version of python  that we are currently working on?')
print('=> function sys.version')
print('9) What does PIP stand for Python?')
print('=> preferred installer program.')
print('10) Mention few built in function in python.')
print('=> Python Built-in Functions      .print function.      .type function.       .input function.       .abs function.        .pow function.       .dir function.       .sorted function.      .max function.')
print('11) What is maximum  possible length of an identifier in Python?')
print('=> 79 characters.')
print('12) What are the benefits of using Python?')
print('=> Top Reasons to Learn Python      .Data science.      .Scientific and mathematical computing.      .Web development.      .Finance and trading.      .System automation and administration.      .Computer graphics.      .Basic game development.      .Security and penetration testing.')